#Service parameters
apiVersion: v1
kind: Service
metadata:
  name: mysql-service 
spec:
  type: LoadBalancer
  ports:
    - port: 3306
  selector:
    app: mysql
---
#Deployment Parameters
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
#Spec seems to provide a template of what the pod should look like
spec:
  #Replicas determine the number of pods created from the image 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql/mysql-server
          name: mysql
          #Used to provide root password, username, password, and database on MYSQL 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: sofe4790u
            - name: MYSQL_DATABASE
              value: myDB 
          ports:
            - containerPort: 3306
              name: mysql